version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ../..:/workspaces:cached
      - dotjulia:/home/vscode/.julia
    network_mode: service:db
    command: sleep infinity

  db:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: msSQ_F123
      MSSQL_PID: Evaluation
    ports:
      - 127.0.0.1:1433:1433

volumes:
  db-data:

  dotjulia:
